### ISSUE TITLE
`instancemethod` problem

### ISSUE THREAD

**Issue by oleksandrzelentsov** [oleksandrzelentsov/snap-sink#3]
```
➜  snap-sink git:(dev) sink
Traceback (most recent call last):
  File "/home/cloudlinux-dev/bin/sink", line 81, in <module>
    files = SyncFile.from_config(cp, args.files)
  File "/home/cloudlinux-dev/bin/sink", line 49, in from_config
    for section in sections:
TypeError: 'instancemethod' object is not iterable
```

**Comment by oleksandrzelentsov** [comment]
solved with 340bd2628a90706bce363f855842ae0e046f4560
